name: Surge Deployer

on: 
  pull_request:
    types: [closed]
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy on SURGE
      if: github.event.pull_request.merged == true
    - run: npm install 
    - run: npm install --save-dev surge
    - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
