name: Surge Deployer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy on SURGE
      run: npm install && npm install --save-dev surge && npm run deploy
